name: DevCard
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'


jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:   
     # This step checks out a copy of your repository.
      - name: My first step - check out repository
        uses: actions/checkout@v4
      - name: devcard
        uses: dailydotdev/action-devcard@2.3.1
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
